name: Docs Guidelines

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/**'
      - '**.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          fix: true
          globs: |
            *.md
            **/*.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fixed docs style
