name: Docs Guidelines

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/**'
      - '**.md'

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Create .markdownlint-cli2.jsonc
        run: |
          echo '{ "fix": true }' > .markdownlint-cli2.jsonc

      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action@v9
        continue-on-error: true
        with:
          globs: |
            docs/**/*.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fixed docs style
